services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://citeeval.duckdns.org/api
    restart: always
    environment:
      - NODE_ENV=production
      - JWT_SECRET=C@itE_eValuAtiOn_SySteM_2026_SeCuRe_X82P9_Lq7
      - DB_HOST=db
      - DB_USER=cite_db_admin
      - DB_PASSWORD=StRonG_Es_PaSs_992!_Xz
      - DB_NAME=cite_es
      - REDIS_URL=redis://redis:6379
      - NEXT_PUBLIC_API_URL=http://citeeval.duckdns.org/api
    depends_on:
      - db
      - redis
    networks:
      - cite_network

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - cite_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - cite_network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cite_es
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ../database/cite_es.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cite_network

networks:
  cite_network:
    driver: bridge

volumes:
  db_data:
